language: minimal

install:
    - sudo apt-get update
    - sudo apt-get install python python-pip -y

script:
    - script/build.sh
    - script/uniq_reject_list.sh

deploy:
    provider: pages
    skip-cleanup: true
    target-branch: master
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
        branch: master
